version: 2

models:
  - name: dim_channels
    description: "Dimension table for Telegram channels"
    columns:
      - name: channel_key
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: channel_name
        description: "Name of the channel"
        tests:
          - not_null

  - name: dim_dates
    description: "Date dimension"
    columns:
      - name: date_key
        description: "Primary key for date"
        tests:
          - unique
          - not_null
      - name: full_date
        description: "Full date representation"

  - name: fct_messages
    description: "Fact table for telegram messages"
    columns:
      - name: message_id
        description: "Original message ID"
        tests:
          - not_null
      - name: channel_key
        description: "Foreign key to dim_channels"
        tests:
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        description: "Foreign key to dim_dates"
        tests:
          - relationships:
              to: ref('dim_dates')
              field: date_key

  - name: fct_image_detections
    description: "Fact table for YOLO image detections"
    columns:
      - name: message_id
        description: "Message ID associated with the image"
        tests:
          - relationships:
              to: ref('fct_messages')
              field: message_id
